package br.cefetmg.inf.util;

public enum RequestType {
    
    //Package 
    NUMPACKAGE, CONFIRMATIONPACKAGE,
    //User
    REGISTERUSER, SEARCHUSER, UPDATEUSER, DELETEACCOUNT, GETUSERLOGIN,
    // Item
    CREATEITEM, DELETEITEM, UPDATEITEM, LISTALLITEM, SEARCHITEMBYID, SEARCHITEMBYNAME,
                SEARCHITEMBYTAG, SEARCHITEMBYTYPE, SEARCHITEMBYTAGANDTYPE,
    // ItemTag
    CREATETAGINITEM, DELETETAGINITEM, LISTALLTAGINITEM, DELETETAGBYITEMID,
    //MAX
    UPDATEALLITEMS, UPDATEALLTAGS, UPDATEALLITEMTAG, LOADITEMS, LOADTAGS, LOADTAGSITEMS, LOADITEMSTAGS;  

}
