package br.cefetmg.inf.util;

public enum RequestType {
    
    //Package 
    NUMPACKAGE, CONFIRMATIONPACKAGE,
    //User
    REGISTERUSER, SEARCHUSER, UPDATEUSER, DELETEACCOUNT, GETUSERLOGIN,
    // Item
    CREATEITEM, DELETEITEM, UPDATEITEM, SEARCHITEMBYNAME, LISTALLITEM,
    // ItemTag
    DELETETAGBYITEMID;
    
}
